# Generated by Django 3.2.9 on 2022-04-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='paid',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='technicianpayment',
            name='amount',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
